'''
script to split sentences for kenlm processing

Authors: Aditya, Abhinav

'''

import json

f = open("demo_file") 		# open file generated by sentence_generate script
l = open("demo_file", 'w+')
a = f.read()
x = a.split('.')
for i in x:
	l.write(i.strip() + "\n")

